name: Automatically Generate requirements.txt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check requirements.txt
        uses: ekvanox/pipreqs-action@master
      - name: Save file
        uses: actions/upload-artifact@v3
        with:
          name: requirements.txt
          path: requirements.txt
